### ISSUE TITLE
fibers and green threads are the same

### ISSUE THREAD

**Issue by baruch** [andrew-canaday/giant_collection_of_programming_links#1]
At least IMO.

Also libwire should be in the green threads group. Coroutines have a different meaning than green threads. That of a single coroutine that does work cooperatively and switch between them, green threads and fibers are user space threads which is what libwire tries to achieve with some very specific design decisions (no mallocs).

**Comment by andrew-canaday** [comment]
Ayo! Thanks much for the input. I believe the usual distinction is:
- threads - kernel scheduled, typically preemptive
- green threads - VM scheduled, preemptive
- fibers - userspace scheduled, cooperative

I could, of course, be wrong, and there are likely variations to each of these schemes which broaden the definition.

As a disclaimer: this repo is not intended to be an exhaustive list of links for a given topic. Rather, it's just a list of things that I've actually stumbled upon, read, and felt like sharing. Nevertheless, I'll check out libwire when I happen upon some time.

Ciao!
-Andrew
